FROM python:3.11.9-slim-bullseye

COPY ./requirements.txt tmp/requirements.txt

RUN pip install --no-cache-dir -r tmp/requirements.txt

RUN mkdir /static

RUN mkdir /logs

COPY ./ /app

WORKDIR /app

ENTRYPOINT ["bash","./entrypoint.dev.sh"]